# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RMAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement')], max_length=10)),
                ('username', models.CharField(max_length=12)),
                ('password', models.TextField()),
            ],
        ),
    ]
