# Generated by Django 2.0.7 on 2018-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RMCredentialsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement')], max_length=10)),
                ('username', models.CharField(max_length=12)),
                ('password', models.TextField()),
            ],
        ),
    ]
