# Generated by Django 2.0.7 on 2018-08-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RMCredentialsSet',
            new_name='RMAccount',
        ),
    ]
