# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-12 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_internjobopening_internnotification_jobopening_notification_placementjobopening_placementnotificatio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='deadline',
            new_name='appDeadline',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='header',
            new_name='heading',
        ),
    ]
